site_name: Hellnet Docs
site_url: https://docs.hellnet.com.br/
repo_url: https://github.com/hellnet-foundation/hellnet-foundation.github.io
repo_name: hellnet-foundation.github.io

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: blue

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

nav:
  - Início: index.md

extra:
  generator: false
