site_name: Hellnet Docs
site_url: https://docs.hellnet.com.br/

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: blue

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

nav:
  - Início: index.md
  - Operação:
      - Infra: infra.md
      - Runbooks: runbooks.md
  - Decisões:
      - ADRs: adr/index.md

extra:
  generator: false
